# Generated by Django 2.1.3 on 2019-11-07 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField()),
                ('cts_previstos', models.IntegerField(blank=True, null=True)),
                ('cts_executados', models.IntegerField(blank=True, default=0, null=True)),
                ('bugs_encontrados', models.IntegerField(blank=True, default=0, null=True)),
                ('cts_cancelados', models.IntegerField(blank=True, default=0, null=True)),
                ('observacao', models.TextField(blank=True, default='', max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'diario',
                'verbose_name_plural': 'diarios',
                'db_table': 'diario',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=80)),
                ('data_inicial', models.DateField()),
                ('dias_execucao', models.IntegerField()),
                ('quantidade_ct', models.IntegerField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'projeto',
                'db_table': 'projeto',
            },
        ),
        migrations.CreateModel(
            name='StatusProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'status',
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='status_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sgteste_app.StatusProjeto'),
        ),
        migrations.AddField(
            model_name='diario',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgteste_app.Projeto'),
        ),
    ]
