# Generated by Django 2.1.3 on 2019-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgteste_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cts_adicionais',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
