# Generated by Django 2.1.3 on 2020-01-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgteste_app', '0002_projeto_cts_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='localizacao',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
