# Generated by Django 2.1.3 on 2020-01-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgteste_app', '0003_projeto_localizacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='localizacao',
            new_name='mudei',
        ),
    ]
