# Generated by Django 2.1.3 on 2020-01-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgteste_app', '0004_auto_20200102_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='mudei',
            new_name='gitlab_file',
        ),
    ]
